set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {pulsadores[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulsadores[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulsadores[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulsadores[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulsadores[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulsadores[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulsadores[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulsadores[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reles[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reles[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reles[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reles[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reles[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reles[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reles[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reles[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inEsp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inEsp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outEsp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outEsp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulsadorEsp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulsadorEsp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {releEsp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {releEsp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports dataReady]


set_property PACKAGE_PIN P12 [get_ports scl]
set_property PACKAGE_PIN P13 [get_ports sda]
set_property PACKAGE_PIN H4 [get_ports clk]
set_property PACKAGE_PIN D14 [get_ports rst]
set_property PACKAGE_PIN B12 [get_ports {inEsp[0]}]; #GPIO27
set_property PACKAGE_PIN H14 [get_ports {inEsp[1]}]; #GPIO18
set_property PACKAGE_PIN M13 [get_ports {outEsp[0]}]; #GPIO5
set_property PACKAGE_PIN L14 [get_ports {outEsp[1]}]; #GPIO19
set_property PACKAGE_PIN P2 [get_ports dataReady]; #GPIO23
set_property PACKAGE_PIN P5 [get_ports {releEsp[0]}] 
set_property PACKAGE_PIN E11 [get_ports {releEsp[1]}] 
set_property PACKAGE_PIN B2 [get_ports {pulsadorEsp[0]}] 
set_property PACKAGE_PIN B1 [get_ports {pulsadorEsp[1]}] 

set_property PACKAGE_PIN A10 [get_ports {pulsadores[0]}] 
set_property PACKAGE_PIN B6 [get_ports {pulsadores[1]}] 
set_property PACKAGE_PIN A5 [get_ports {pulsadores[2]}] 
set_property PACKAGE_PIN B5 [get_ports {pulsadores[3]}] 
set_property PACKAGE_PIN A4 [get_ports {pulsadores[4]}]
set_property PACKAGE_PIN A3 [get_ports {pulsadores[5]}]
set_property PACKAGE_PIN B3 [get_ports {pulsadores[6]}]
set_property PACKAGE_PIN A2 [get_ports {pulsadores[7]}]

set_property PACKAGE_PIN N14 [get_ports {reles[0]}] 
set_property PACKAGE_PIN M14 [get_ports {reles[1]}] 
set_property PACKAGE_PIN C4 [get_ports {reles[2]}]
set_property PACKAGE_PIN B13 [get_ports {reles[3]}]
set_property PACKAGE_PIN N10 [get_ports {reles[4]}]
set_property PACKAGE_PIN M10 [get_ports {reles[5]}]
set_property PACKAGE_PIN B14 [get_ports {reles[6]}]
set_property PACKAGE_PIN D3 [get_ports {reles[7]}]

## Configuration options, use for all designs
#set_property CONFIG_VOLTAGE 3.3 [current_design]
#set_property CFGBVS VCCO [current_design]