esphome:
  name: esp8266

esp8266:
  board: esp01_1m

# Enable logging
logger:

mqtt:
  broker: 192.168.30.6
  username: !secret mqtt_user
  password: !secret mqtt_password
  id: mqtt_client_esp8266

i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

rc522_spi:
  cs_pin: GPIO15
  update_interval: 1s
  on_tag:
    then:
      - mqtt.publish:
          topic: ESP8266/RC522/Tag
          payload: !lambda 'return x;'

binary_sensor:
  - platform: rc522
    uid: 07-77-B6-B5
    name: "RFID Llavero"

  - platform: rc522
    uid: E3-C3-DD-3E
    name: "RFID Tarjeta"
 
sensor:
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 20s
    state_topic: ESP8266/BH1750/Luminosidad
    
  - platform: aht10
    temperature:
      name: "AHT10 Temperature"
      state_topic: ESP8266/AHT10/Temperatura
    humidity:
      name: "AHT10 Humidity"
      state_topic: ESP8266/AHT10/Humedad  
    update_interval: 15s
    
  - platform: ms5611
    temperature:
      name: "MS5611 Temperature"
      state_topic: ESP8266/MS5611/Temperatura
    pressure:
      name: "MS5611 Pressure"
      state_topic: ESP8266/MS5611/Presion
    address: 0x77
    update_interval: 10s
    
  - platform: tcs34725
    red_channel:
      name: "TCS34725 Red Channel"
      state_topic: ESP8266/TCS34725/Rojo
    green_channel:
      name: "TCS34725 Green Channel"
      state_topic: ESP8266/TCS34725/Verde
    blue_channel:
      name: "TCS34725 Blue Channel"
      state_topic: ESP8266/TCS34725/Azul
    clear_channel:
      name: "TCS34725 Clear Channel"
      state_topic: ESP8266/TCS34725/Claro
    illuminance:
      name: "TCS34725 Illuminance"
      state_topic: ESP8266/TCS34725/Luminosidad
    color_temperature:
      name: "TCS34725 Color Temperature"
      state_topic: ESP8266/TCS34725/Temperatura
    #gain: 1x
    integration_time: auto
    #glass_attenuation_factor: 1.0
    address: 0x29
    update_interval: 5s
    
  - platform: ultrasonic
    trigger_pin: 1
    echo_pin: 3
    name: "Ultrasonic Sensor"
    update_interval: 5s
    state_topic: ESP8266/Ultrasonic
    
# Enable Home Assistant API
#api:
#  encryption:
#    key: "8h5rKIDbWA+BtWXAWzaI2gZKiZJ7fUYUaVYlOHCtL+U="

ota:
  password: "5c3648f57b41ae5e2f73ddbc508b9a42"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266 Fallback Hotspot"
    password: "a4Mb5aoQe7ha"

captive_portal:
    