esphome:
  name: esp8266-sensoresi2c

esp8266:
  board: esp01_1m

# Enable logging
logger:

mqtt:
  broker: 192.168.30.50
  username: !secret mqtt_user
  password: !secret mqtt_password
  id: esp8266_sensoresi2c

i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a

# Enable Home Assistant API
# api:
#   encryption:
#     key: "9K7zpNy7JVn5TR8u5cEeUs6/jU2mDxs/3FQNIav1ElQ="

sensor:
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 60s
    state_topic: ESP8266/BH1750/Luminosidad
    
  - platform: aht10
    temperature:
      name: "AHT10 Temperature"
      state_topic: ESP8266/AHT10/Temperatura
    humidity:
      name: "AHT10 Humidity"
      state_topic: ESP8266/AHT10/Humedad  
    update_interval: 60s
    
  - platform: ms5611
    temperature:
      name: "MS5611 Temperature"
      state_topic: ESP8266/MS5611/Temperatura
    pressure:
      name: "MS5611 Pressure"
      state_topic: ESP8266/MS5611/Presion
    address: 0x77
    update_interval: 60s
    
  - platform: tcs34725
    red_channel:
      name: "TCS34725 Red Channel"
      state_topic: ESP8266/TCS34725/Rojo
    green_channel:
      name: "TCS34725 Green Channel"
      state_topic: ESP8266/TCS34725/Verde
    blue_channel:
      name: "TCS34725 Blue Channel"
      state_topic: ESP8266/TCS34725/Azul
    clear_channel:
      name: "TCS34725 Clear Channel"
      state_topic: ESP8266/TCS34725/Claro
    illuminance:
      name: "TCS34725 Illuminance"
      state_topic: ESP8266/TCS34725/Luminosidad
    color_temperature:
      name: "TCS34725 Color Temperature"
      state_topic: ESP8266/TCS34725/Temperatura
    #gain: 1x
    integration_time: auto
    #glass_attenuation_factor: 1.0
    address: 0x29
    update_interval: 60s
    
ota:
  password: "3b01505b043654b8d846f055577876e0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Sensoresi2C"
    password: "KnqS8u1ynx8f"

captive_portal:
    
